### PR TITLE
Created Rainbow LED example.

### PR DESCRIPTION
**Pull request by MicahStevens**
I adapted some code I found on http://krazydad.com/tutorials/makecolors.php - thought it would be useful to others.

### CODE REVIEW

**Comment by projectgus** [comment]
Hi Micah,

Sorry for the slow reply on this issue.

This looks great! I just want to check with @jbum that he's OK with us incorporating something based on his code as an example. (Jim - this code is for displaying rainbow colours and a 4x4x4 LED cube, http://www.freetronics.com.au/products/cube4-4x4x4-rgb-led-cube . The hardware and the library are open source.)

Angus

**Comment by jbum** [comment]
Sure, no problem.

Jim

**Comment by projectgus** [comment]
Thanks Jim!

**Comment by MicahStevens** [comment]
@jbum @projectgus Thanks!

**Pull request merged**
